Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/08/2020
Var
// Seção de Declarações das variáveis 
     f,c: real;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    Escreva ("Insira a temp F: ")
    leia(f)
    c <- (f - 32)*(5*9)
    Escreva("A temp em Celsius é : ", c)
Fimalgoritmo