Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/08/2020
Var
// Seção de Declarações das variáveis 
    C,F : real;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreva ("Digite a temperatura em C": )
     leia(c)
     F <- (9*C + 160)/5
     Escreva("A temp em F:", F)
     
Fimalgoritmo